contact us page
shriya030/CS-Hut pull request #19
Opened 2021-06-10 14:06 UTC by kumarishalini6

# Description
I have created contact us component 

Fixed #1 

![CS Hut - Personal - Microsoft​ Edge 6_10_2021 07_33_01 PM](https://user-images.githubusercontent.com/69043944/121539270-00388d80-c9b2-11eb-891c-dc8bd9e90ecb.png)

2021-06-10 14:08 UTC, kumarishalini6 commented
@shriya030 please have a look and if you want any changes let me know. Thanks

2021-06-11 05:01 UTC, aj3011 requested changes
1. Remove the blur effect but don't remove box-shadow effect
2. Change the background color of the submit button and contact us title to sky blue and text color to black.

2021-06-11 05:40 UTC, kumarishalini6 commented
> 1. Remove the blur effect but don't remove box-shadow effect
> 2. Change the background color of the submit button and contact us title to sky blue and text color to black.

I didn't add any blur effect , can you please explain where you have seen blur effect?
I 'll make other changes.

2021-06-11 05:44 UTC, aj3011 commented
![Capture](https://user-images.githubusercontent.com/71029690/121636832-1fb0e280-caa6-11eb-9702-db426e78fb32.PNG)

Blur part in box-shadow

2021-06-11 05:45 UTC, kumarishalini6 commented
> ![Capture](https://user-images.githubusercontent.com/71029690/121636832-1fb0e280-caa6-11eb-9702-db426e78fb32.PNG)
> 
> Blur part in box-shadow

 isn't blur effect , it is part of box shadow , ok I'll remove that

2021-06-11 11:00 UTC, kumarishalini6 commented
@shriya030 @aj3011  I have made all the changes please have a look

2021-06-12 06:55 UTC, shriya030 commented on src/App.js
>      </div>
Expected corresponding JSX closing tag for <> (79:4)

  77 |       <ScrollToTop />
  78 |
> 79 |     </div>
     |     ^
  80 |   );
  81 | }
  82 |

2021-06-12 06:57 UTC, shriya030 commented on src/App.js
>      </div>
Kindly resolve the errors.

2021-06-12 07:34 UTC, shriya030 approved these changes

2021-06-12 07:35 UTC, shriya030 commented
@kumarishalini6 Great 🎉

2021-06-12 07:37 UTC, kumarishalini6 commented
> @kumarishalini6 Great 🎉

Thanks😊

2021-06-12 08:02 UTC, aj3011 approved these changes

2021-06-12 08:02 UTC, merged