Added Python resources
shriya030/CS-Hut pull request #33
Opened 2021-06-12 18:11 UTC by himanshu007-creator

# Description

added resources for python language
resolved #32 

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-06-14 16:24 UTC, shriya030 requested changes
Resolve merge conflicts!

2021-06-15 05:33 UTC, himanshu007-creator commented
> Resolve merge conflicts!

resolved

2021-06-21 07:29 UTC, shriya030 approved these changes

2021-06-21 07:29 UTC, merged

2021-06-21 07:29 UTC, himanshu007-creator commented
Thamks :)