Ayushsoni1010
shriya030/CS-Hut pull request #43
Opened 2021-06-15 15:05 UTC by ayushsoni1010

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.
- added guidelines to the contributing.md file

Fixed #42 

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
-  New feature (non-breaking change which adds functionality)
-  This change requires a documentation update

# Checklist:

-  I have pulled the latest changes in the repository
-  I have squashed my commits
-  My code follows the style guidelines of this project
-  I have performed a self-review of my own code
-  I have commented on my code, particularly in hard-to-understand areas
-  I have made corresponding changes to the documentation
-  My changes generate no new warnings

2021-06-15 15:09 UTC, shriya030 requested changes
We don't have the PR template which you have put in this. Kindly change that.

2021-06-15 15:10 UTC, shriya030 commented on contributing.md
> +- Each participant/contributor will be assigned **2 issues (max)** at a time to work on.
Remove this line

2021-06-15 15:12 UTC, ayushsoni1010 commented on contributing.md
> +- Each participant/contributor will be assigned **2 issues (max)** at a time to work on.
okay, wait a min

2021-06-15 15:16 UTC, ayushsoni1010 commented on contributing.md
> +- Each participant/contributor will be assigned **2 issues (max)** at a time to work on.
Done

2021-06-15 15:45 UTC, ayushsoni1010 commented
Alright ?

2021-06-16 07:38 UTC, shriya030 approved these changes

2021-06-16 07:50 UTC, aj3011 approved these changes

2021-06-16 15:14 UTC, shriya030 approved these changes

2021-06-16 15:14 UTC, merged