Link Feedback Form
shriya030/CS-Hut pull request #54
Opened 2021-06-18 08:32 UTC by rishabhrathore055

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixed #20 

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-06-18 15:41 UTC, shriya030 requested changes
Kindly remove the repeated code

2021-06-18 15:41 UTC, shriya030 commented on src/HomePage/Footer.js
>  }
Kindly remove the repeated code.

2021-06-18 15:58 UTC, rishabhrathore055 commented
@shriya030 pls review it

2021-06-19 16:40 UTC, shriya030 approved these changes

2021-06-19 18:59 UTC, aj3011 approved these changes

2021-06-19 19:00 UTC, merged

2021-06-19 19:33 UTC, rishabhrathore055 commented
@shriya030 please assign levels